apiVersion: v1
kind: Service
metadata:
  name: uptime #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: uptime
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.76
  loadBalancerIP: 192.168.0.76
  ports:
    - protocol: TCP
      port: 80 #Service port
      targetPort: 8080 #The port for the container